# Generated by Django 5.0.6 on 2024-07-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ammunation', '0014_alter_arma_calibre_alter_venta_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arma',
            old_name='categoria',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='arma',
            name='calibre',
             field=models.CharField(choices=[('Pistola', 'Pistola'), ('Escopeta', 'Escopeta'), ('Subfusil', 'Subfusil'), ('Fusil', 'Fusil'), ('Francotirador', 'Francotirador')], max_length=13),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(choices=[('Curanilahue', 'Curanilahue'), ('Concepción', 'Concepción'), ('Colina', 'Colina')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PREPARADO', 'PREPARADO'), ('ENTREGADO', 'ENTREGADO'), ('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('ENVIADO', 'ENVIADO')], default='EN PREPARACIÓN', max_length=30),
        ),
    ]
