# Generated by Django 5.0.6 on 2024-07-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ammunation', '0015_rename_categoriaria_arma_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='calibre',
            field=models.CharField(choices=[('fusil', 'fusil'), ('pistola', 'pistola'), ('escopeta', 'escopeta'), ('francotirador', 'francotirador'), ('subfusil', 'subfusil')], max_length=13),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(choices=[('colina', 'colina'), ('curanilahue', 'curanilahue'), ('Concepción', 'Concepción')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('ENVIADO', 'ENVIADO'), ('PREPARADO', 'PREPARADO'), ('ENTREGADO', 'ENTREGADO'), ('EN PREPARACIÓN', 'EN PREPARACIÓN')], default='EN PREPARACIÓN', max_length=30),
        ),
    ]
