# Generated by Django 5.0.6 on 2024-07-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ammunation', '0016_alter_arma_calibre_alter_perfil_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='calibre',
            field=models.CharField(choices=[('pistola', 'pistola'), ('fusil', 'fusil'), ('francotirador', 'francotirador'), ('subfusil', 'subfusil'), ('escopeta', 'escopeta')], max_length=13),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(choices=[('curanilahue', 'curanilahue'), ('colina', 'colina'), ('Concepción', 'Concepción')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('ENTREGADO', 'ENTREGADO'), ('ENVIADO', 'ENVIADO'), ('PREPARADO', 'PREPARADO')], default='EN PREPARACIÓN', max_length=30),
        ),
    ]
